import { Suspense } from "react";
import { Inter } from "next/font/google";

import Header from "@/components/header/Header";
import "./globals.css";
import Loader from "@/components/loader/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          height: "100vh",
        }}
      >
        <Suspense fallback={<Loader />}>
          <Header islogin={true} />
        </Suspense>
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  );
}
